### ISSUE TITLE
Adding New Array Element Creates Duplicate References [BUG] 

### ISSUE THREAD

**Issue by chadefranklin** [mackysoft/Unity-SerializeReferenceExtensions#10]
### What happened?

When drawing an array of serializable classes (as SerializeField) that contains a SubclassSelector, adding a new instance to the array creates duplicate references to the subclass which is only fixed once manually choosing an implementation from the dropdown. I have attached a video of the issue.

https://user-images.githubusercontent.com/55667412/160413447-2d90017f-d187-496d-998c-df2c0294c524.mp4

### Package Version

1.1.2

### Unity Version

2020.3.30f1

**Comment by chadefranklin** [comment]
I guess this one is a Unity bug, it doesn't seem like there's a way to escape the issue. No matter how you organize the data serialized by reference, someone else may want to put that data inside a SerializeField object array.

**Comment by LastAssertor** [comment]
When the list is updated, I try to serialize and deserialize the contents of the list, which avoids this problem.

I used the 'OnValueChangedAttribue' of '[NaughtyAttributes](https://github.com/dbrizov/NaughtyAttributes)' to detect field updates.

Hope to give you some inspiration.

```csharp

using NaughtyAttributes;

public interface ICommand {
	void Execute();
}

[Serializable]
public class SetInt:ICommand{
	public string key;
	public int value;
	public void Execute(){
		PlayerPrefs.SetInt(key,value);
	}
}

[Serializable]
public class SetBool:ICommand{
	public string key;
	public bool value;
	public void Execute(){
		PlayerPrefs.SetBool(key,value);
	}
}

[Serializable]
public class DayEvent{
	public List<int> days=new();
        [SerializeReference, SubclassSelector]
        public List<ICommand> commands = new();
	public bool CanExecute(int day){
		return days.Contains(day);
	}
        public void Execute(){
            commands.ForEach(c => c.Execute());
        }
}

public class DayManager:MonoBehaviour{
	public int day;
#if UNITY_EDITOR
        [OnValueChanged("OnDayEventsChanged")]
#endif
	public List<DayEvent> dayEvents=new();
#if UNITY_EDITOR
	public void OnDayEventsChanged(){
        List<DayEvent> list = new();
        foreach (var ev in dayEvents)
        {
            var newEv = ev;
            JsonUtility.FromJsonOverwrite(JsonUtility.ToJson(newEv, true), newEv);
            list.Add(newEv);
        }
        dayEvents.Clear();
        dayEvents.AddRange(list);
	}
	public void Test(){
		dayEvents.ForEach(x=>{
			if(x.CanExecute(day)){
				x.Execute();
			}
		});
	}
#endif
}
```

**Comment by chadefranklin** [comment]
Interesting, I may have to look into NaughtyAttributes some more, thanks for the tip! I have also filed a bug report and will see what Unity thinks.

**Comment by mackysoft** [comment]
> I guess this one is a Unity bug (or is this desirable behavior in some circumstances?), it doesn't seem like there's a way to escape the issue. No matter how you organize the data serialized by reference, someone else may want to put that data inside a SerializeField object array.

Hmm, as mentioned above, this is a Unity specification. When you add a new element to an array in the inspector, the previous element is copied.
So in the case of `SerializeReference`, the element reference is copied.

Whether this behavior is desirable for `SerializeReference` will depend on the use case.

If copying the reference is undesirable, I think it is appropriate to either manually create a new object or use a solution such as the one described above.
