### ISSUE TITLE
[IMPROVE] Allow Script Location Move Without Losing Serialized Data

### ISSUE THREAD

**Issue by NickMercer** [mackysoft/Unity-SerializeReferenceExtensions#12]
### Improvement destription

So currently, it looks like if you Serialize a reference (say, to an object implementing an interface) through the SubclassSelector attribute, and then you move that script file, you lose all your serialized data for every reference that used that subclass/implementation.

Is there a way this could be worked around and improved? Or is this a limitation of SerializedReference on Unity's part?

I absolutely love these extensions, but it feels a bit too dangerous to use something that could wipe out tons of my serialized data if I ever refactor and forget I can't move certain scripts.

**Comment by mackysoft** [comment]
It is a limitation (or issue?) of `SerializeReference`.
`SubclassSelector` is a function that provide a useful interface in the inspector. It does not intervene in serialization.

Perhaps this thread will help you.
https://forum.unity.com/threads/serializereference-data-loss-when-class-name-is-changed.736874

**Comment by NickMercer** [comment]
Got it, thanks for clearing that up. It might be worth mentioning in the readme just as a PSA, since people (like myself) may not know that about SerializeReference and could be surprised when they lose data after moving/renaming a script.

I appreciate the quick response and helpful link. This is a great set of extensions for Unity.

**Comment by mackysoft** [comment]
Indeed, I have added a remark about this issue to the README, as it is a problem that is likely to be encountered when using `SerializeReference`.
https://github.com/mackysoft/Unity-SerializeReferenceExtensions#if-the-type-is-renamed-the-reference-is-lost

Thanks for the feedback!
