### ISSUE TITLE
[BUG] [SubclassSelector] Does Not Support Concrete Base Class

### ISSUE THREAD

**Issue by 2kCarlos** [mackysoft/Unity-SerializeReferenceExtensions#13]
## Desired Behavior
It is possible to create an instance of a field in the Unity inspector, on a field marked `[SerializeReference, SubclassSelector]`, whose data type is a concrete, pure C# data.

## Actual Behavior
Only `<null>` shows in the Unity inspector on a field marked `[SerializeReference, SubclassSelector]`, whose data type is a concrete, pure C# data.

### Code example:
```cs
using System;
using UnityEngine;

public class ReferenceTester : MonoBehaviour {
    [Serializable]
    public class Data {
        public int intValue;
    }

    [SerializeReference, SubclassSelector] private Data example;
}
```

![image](https://user-images.githubusercontent.com/25470751/162556506-547fa740-560e-4f2a-ae87-e20cfc79aa2b.png)
![image](https://user-images.githubusercontent.com/25470751/162556638-ab038b8d-9786-417c-b8ad-55daadd45603.png)

### Package Version

1.1.4

### Unity Version

2021.2.15f1

**Comment by 2kCarlos** [comment]
Thanks so much! :)

**Comment by mackysoft** [comment]
This update will be applied soon!
