### ISSUE TITLE
[IMPROVE]  Examples as Samples

### ISSUE THREAD

**Issue by h1v4n** [mackysoft/Unity-SerializeReferenceExtensions#14]
### Improvement destription

In Unity 2021 I get a warning about cs files from a package without asmdef. Could you provide the Example folder as a Sample instead?

https://docs.unity3d.com/2019.4/Documentation/Manual/cus-samples.html

Thanks!

**Comment by mackysoft** [comment]
Changes have been made to support Samples. This will be applied to the version to be released soon.

Thanks!

**Comment by h1v4n** [comment]
Thanks for the update!

But now a different warning is shown:

> A meta data file (.meta) exists but its folder 'Packages/com.mackysoft.serializereference-extensions/Samples~' can't be found, and has been created. Empty directories cannot be stored in version control, so it's assumed that the meta data file is for an empty directory in version control. When moving or deleting folders outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

**Comment by mackysoft** [comment]
I have released a new version with the `Samples~.meta` file removed.
You will no longer receive warnings!

Thanks to the clear logs, I was able to correct the issue immediately.
