### ISSUE TITLE
[IMPROVE] Subclass Selector Dropdown Menu

### ISSUE THREAD

**Issue by j-schoch** [mackysoft/Unity-SerializeReferenceExtensions#21]
### Improvement description

I would love it if when using `AddTypeMenu` attribute to show a custom display name in the `SubclassSelector` dropdown menu, it would support using paths in order to separate the dropdown contents into categories & submenus.  Similar to the AddComponent menu and other Unity menu attributes like `ContextMenu`, `AddMenu`, `CreateAssetMenu` etc.

This would allow for a more scalable interface and organization in the editor when working with larger projects.

Thanks

**Comment by yellowisher** [comment]
It already has such feature.
But these is a minor bug that path length difference is not considered.
So if you have _any_ different sub category(which is likely), it would work!

![image](https://user-images.githubusercontent.com/22076358/186440256-609cdbae-5a30-4712-afbb-a93fc10d82d8.png)

**Comment by j-schoch** [comment]
understood! thank you.
