### ISSUE TITLE
[BUG] References lost after changing asmdefs

### ISSUE THREAD

**Issue by celojevic** [mackysoft/Unity-SerializeReferenceExtensions#28]
### What happened?

I decided to move some scripts into asmdefs today and all my interface list items lost their references. This is due to the asm not being automatically updated after recompile.

Before it was referencing the default C# asm:
`type: {class: SetPlayFabDataOption, ns: Entities.Npcs.Dialogues, asm: Assembly-CSharp}`

When it should be referencing the new one:
`type: {class: PlayFabDataConditionalDialogue, ns: Entities.Npcs.Dialogues, asm: Tombstone}`

Simply changing it in a text editor to the correct asm fixes it, but Im sure this can and should be automated :)

### Package Version

1.1.7

### Unity Version

2021.3.24f1

**Comment by mackysoft** [comment]
Hi. Sorry, OSS has been difficult to deal with for a while.

It was very late in responding, so this may be an issue that has already been resolved, but wouldn't `MovedFromAttribute` work?
Here is the reference thread: https://forum.unity.com/threads/serializereference-data-loss-when-class-name-is-changed.736874/

Please re-open this issue if you are having problems.
