### ISSUE TITLE
Why no struct support?

### ISSUE THREAD

**Issue by niscolas** [mackysoft/Unity-SerializeReferenceExtensions#3]
I haven't found any Contributing or Questions guidelines, so sorry for the unformatted Issue 😢 

There's any particular reason for support for Classes but not structs? 
It's a very common use case (for me at least) use structs and implement interfaces.

**Comment by mackysoft** [comment]
Hi.

I personally do not like to keep the struct as an interface because of the boxing that occurs.
However, I decided that there was no need to constrain it, so I supported structs in the new update. #4 

By the way, what kind of use do you envision? (Just curious to know)

**Comment by niscolas** [comment]
There's no actual need for specifically using structs, I just see as a good practice to use them when I don't need the Class full feature set. For simple data only structures for instance.
Many times I use the architecture of this post too: https://straypixels.net/statuseffects-framework/ and for the "Buff Data" I use structs.

Happy to know that this feature is now supported, thank you! 😄
