### ISSUE TITLE
[BUG] SubClassSelectorDrawer.cs lagging when i write in a field

### ISSUE THREAD

**Issue by Sebax95** [mackysoft/Unity-SerializeReferenceExtensions#36]
### What happened?

Hi!
There is a problem when i try to write in a field that use the PropertyDrawer "SubclassSelector"
[Video](https://gyazo.com/148854b9273f3e1ffcb01e8a45b78a16)
the variable is an interface that use UniTask<struct>
maybe the problem is in the method GetTypeName

### Package Version

1.1.7

### Unity Version
2021.3.27
_No response_

**Comment by mackysoft** [comment]
Thanks.
Can you provide the source code of the corresponding interface, abstract type, and concrete type definition?

**Comment by Sebax95** [comment]
Sure!
![image](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/49926152/4606df42-2b24-4cb8-a333-afd179544958)
![image](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/49926152/f421030d-a6e7-499b-8f39-9770a8e25c9d)
![image](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/49926152/596473e4-a534-4b45-8c2c-9314bea27bc8)
hope this can help you!

**Comment by mackysoft** [comment]
Sorry, I've been busy and delayed in supporting the library.

In the video, FlushDirty is causing overhead, but I could not reproduce it here.
One thing I would like to confirm, the AssetLoader component seems to have an editor extension, does it do anything when there is a change to the properties?

It is possible that SubclassSelector is causing frequent overhead, but I need more information to respond.

If you are willing to reply, please re-open.
