### ISSUE TITLE
[IMPROVE] use JsonUtility to serialise and then deserialise into the new type

### ISSUE THREAD

**Issue by Mudloop** [mackysoft/Unity-SerializeReferenceExtensions#37]
### Improvement destription

When changing a type, it would be good to serialise the current value, and then deserialise into the new object instead of using the activator. That way, any properties they share will be retained. 

I would also add a “make unique” button that just clones the object (also using jsonutility), useful after a “duplicate array” operation. This could be a little button next to the selector (or a … button that opens a menu).

**Comment by jlaprof** [comment]
The asset is excellent, and both are nice suggestions; the first one is highly appreciated if we use a lot of inheritance, and the second one, you usually won't want a duplicate reference. An easy way to make it unique seems logical... not sure how to implement the UI/UX part...

**Comment by mackysoft** [comment]
Hi @Mudloop 
Sorry for the delay.

The latest release supports restoring values from JSON.
https://github.com/mackysoft/Unity-SerializeReferenceExtensions/releases/tag/1.2.0
