### ISSUE TITLE
[BUG] 在Unity点击运行时会报错"Objects are trying to be loaded during a domain backup. This is not allowed as it will lead to undefined behaviour!"

### ISSUE THREAD

**Issue by acmendu** [mackysoft/Unity-SerializeReferenceExtensions#38]
### What happened?

[BUG] 在Unity点击运行时会报错"Objects are trying to be loaded during a domain backup. This is not allowed as it will lead to undefined behaviour!",并且随着使用[SerializeReference, SubclassSelector]的频率而增加，是否时我使用不当还是本身的BUG，需要您的帮助

### Package Version

1.1.7和1.1.9都有此问题

### Unity Version

2021.3.9f1c1

**Comment by mackysoft** [comment]
I have been busy and delayed in responding.
I will need a more detailed understanding of the situation in order to provide support. If you can reply, please re-open this issue.
