### ISSUE TITLE
[IMPROVE] Easy way to copy value

### ISSUE THREAD

**Issue by jlaprof** [mackysoft/Unity-SerializeReferenceExtensions#40]
It would be great it there is an easy way to copy/paste the values of the subclasses, for example with the context menu.

![image](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/94906537/c51b82fd-9e69-49bf-b132-5b31694554d3)

**Comment by mackysoft** [comment]
Hi @jlaprof !

Copy and paste functionality has been added in the latest release.
https://github.com/mackysoft/Unity-SerializeReferenceExtensions/releases/tag/1.2.0

![image](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/13536348/8bd44d4d-02a9-4aa5-9db0-0817d80c2391)
