### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by whynames** [mackysoft/Unity-SerializeReferenceExtensions#45]
### What happened?

A bug happened!

Selector doesn't draw anything and gives this error

`NullReferenceException: Object reference not set to an instance of an object
UnityEngine.GUILayoutEntry.ApplyStyleSettings (UnityEngine.GUIStyle style) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/LayoutEntry.cs:72)
UnityEngine.GUILayoutEntry.set_style (UnityEngine.GUIStyle value) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/LayoutEntry.cs:31)
UnityEngine.GUILayoutEntry..ctor (System.Single _minWidth, System.Single _maxWidth, System.Single _minHeight, System.Single _maxHeight, UnityEngine.GUIStyle _style, UnityEngine.GUILayoutOption[] options) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/LayoutEntry.cs:61)
UnityEngine.GUILayoutUtility.DoGetRect (System.Single minWidth, System.Single maxWidth, System.Single minHeight, System.Single maxHeight, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUILayoutUtility.cs:482)
UnityEngine.GUILayoutUtility.GetRect (System.Single minWidth, System.Single maxWidth, System.Single minHeight, System.Single maxHeight, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUILayoutUtility.cs:476)
UnityEditor.EditorGUILayout.GetControlRect (System.Boolean hasLabel, System.Single height, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorGUILayout.cs:2104)
Sirenix.Utilities.Editor.SirenixEditorGUI.ToolbarSearchField (System.String searchText, System.Boolean forceFocus, System.Single marginLeftRight) (at <d5a36a96b2ad42b898b2ec8b30fb6453>:0)
Sirenix.Utilities.Editor.InstanceCreatorWindow.OnGUI () (at <d5a36a96b2ad42b898b2ec8b30fb6453>:0)
UnityEditor.HostView.OldOnGUI () (at /Users/bokken/build/output/unity/unity/Editor/Mono/HostView.cs:268)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:351)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)`

### Package Version

1.1.9

### Unity Version

2021.3.33f

**Comment by mackysoft** [comment]
Hi @whynames .

It is difficult to determine the cause because the stack trace does not seem to contain any lines of code for this library.
Can you provide a video of this bug happening?

**Comment by whynames** [comment]
Yeah, I noticed it. Weird thing is it was working when I first tried, but doesn't now

https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/73838734/714dd772-6f00-4d11-8126-d93328e94ebb

I can see it detects the classes but can't draw, because vertical sizes of the drawers are like size of how many of the inherited ones would fit

**Comment by mackysoft** [comment]
Umm...
From the video, the interface does not appear to be from this library.

I have tried drawing with same SerializeReferenceExtensions library and Unity version and it works fine.
![image](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/13536348/30c87c99-ec8b-432c-b9f4-2fd9064ba976)

**Comment by whynames** [comment]
For anyone wondering, problem was odin inspector editor override, just also add [DrawWithUnity] attribute to your field. It is hard to spot since it is inconsistent.

**Comment by mackysoft** [comment]
@whynames 
Okay, I have never used Odin Inspector, but if I give it the `DrawWithUnity` attribute, will the `SubclassSelector` functionality work perfectly?

For example, as follows.
```cs
[SerializeReference, SubclassSelector, DrawWithUnity]
private IHoge m_Hoge;
```

**Comment by whynames** [comment]
It looks as your screenshot, but my classes didn't have many subclasses, only classes inherit from the interface

**Comment by mackysoft** [comment]
Thanks. If the subclass selection is working properly, there should be no problem.
