### ISSUE TITLE
[BUG] Error "Value cannot be null." when element of list is set to null.

### ISSUE THREAD

**Issue by Qriva** [mackysoft/Unity-SerializeReferenceExtensions#50]
### What happened?

Hello, I have an array of serializable objects like this:
`[SerializeReference, SubclassSelector] public ComposerConfiguration[] configurations;`
The `ComposerConfiguration` is abstract class and base for other classes. When I try to add new element in the inspector I can correctly change <null> to selected subclass from dropdown, however when the class is selected and I want to assign null again I get this error:
```
ArgumentNullException: Value cannot be null.
Parameter name: type
UnityEngine.JsonUtility.FromJson (System.String json, System.Type type) (at <e0dfe14b531f4aef959546c48a6f003b>:0)
MackySoft.SerializeReferenceExtensions.Editor.ManagedReferenceUtility.SetManagedReference (UnityEditor.SerializedProperty property, System.Type type) (at ./Library/PackageCache/com.mackysoft.serializereference-extensions@93d7e13f62/Editor/ManagedReferenceUtility.cs:19)
MackySoft.SerializeReferenceExtensions.Editor.SubclassSelectorDrawer.<GetTypePopup>b__10_1 (MackySoft.SerializeReferenceExtensions.Editor.AdvancedTypePopupItem item) (at ./Library/PackageCache/com.mackysoft.serializereference-extensions@93d7e13f62/Editor/SubclassSelectorDrawer.cs:119)
MackySoft.SerializeReferenceExtensions.Editor.AdvancedTypePopup.ItemSelected (UnityEditor.IMGUI.Controls.AdvancedDropdownItem item) (at ./Library/PackageCache/com.mackysoft.serializereference-extensions@93d7e13f62/Editor/AdvancedTypePopup.cs:135)
```
Am I possibly doing something wrong or it's just a bug? How to fix this?

One note that might possibly help, there is another abstract class between the used one and base one like this:
```
AbstractClassA : ComposerConfiguration
ActualClassB : AbstractClassA 
```

### Package Version

1.2.1

### Unity Version

2022.3.6

**Comment by mackysoft** [comment]
Thank you for the report!
Here is the version where the issue has been fixed.
https://github.com/mackysoft/Unity-SerializeReferenceExtensions/releases/tag/1.2.2
