### ISSUE TITLE
[BUG] I found a bug with foldout icon

### ISSUE THREAD

**Issue by AndrewNovakP** [mackysoft/Unity-SerializeReferenceExtensions#53]
Hi. Element 0 Foldout icon over label text
![image](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/6072592/e4094caa-1bbc-4d5b-90e4-7ef994051f4c)

### Package Version

1.1.2

### Unity Version

2023.2.10

**Comment by mackysoft** [comment]
Hi. Could you explain in more detail what's happening?

**Comment by mackysoft** [comment]
I was able to reproduce it with 2023.2.10f1 and 1.2.2. I'll fix it.

**Comment by mackysoft** [comment]
Hi @AndrewNovakP 

Latest release that includes the bug fixes is here!
https://github.com/mackysoft/Unity-SerializeReferenceExtensions/releases/tag/1.3.0

**Comment by AndrewNovakP** [comment]
> Hi @AndrewNovakP
> 
> Latest release that includes the bug fixes is here! https://github.com/mackysoft/Unity-SerializeReferenceExtensions/releases/tag/1.3.0

Thanks ^_^
