### ISSUE TITLE
[FEATURE] Can you make this work without the custom attribute?

### ISSUE THREAD

**Issue by marcusx2** [mackysoft/Unity-SerializeReferenceExtensions#58]
### Feature destription

I don't know how Odin inspector does it, but they support serialize reference in the inspector as well out of the box, without the need of modifying code, as if it was a Unity native feature.

**Comment by mackysoft** [comment]
Sorry, but unfortunately that's not possible.

Odin allows for extensive editor customization by having components inherit SerializedMonoBehaviour.
This package, on the other hand, strives for small extensions and minimal package dependencies, so it does not extend the entire project in a major way, as Odin does.
