### ISSUE TITLE
[FEATURE] `[AddTypeMenu]` with dynamic string value

### ISSUE THREAD

**Issue by Antoshidza** [mackysoft/Unity-SerializeReferenceExtensions#64]
### Feature description

I have `IEffect` and some wrapper class like `CompositeEffect` which contains `IEffect` and `IProvider<int>` to repeat effect execution certain times. In editor it looks like this:
![image](https://github.com/user-attachments/assets/204621a3-9696-403b-9863-53cb47ca0aac)
And when it not expanded I see only `Element 1 Composite Effect`.

It would be perfect if I could see something like: `Element 1 Composite Effect: Draw` / `Element 1 Draw (composite)` / `Element 1 Draw`. 

I think it could be down like Odin does in it's attributes, where we can specify method name to get `string` dynamically instead of specify const string value.

**Comment by Antoshidza** [comment]
One another way would be to use additional `bool useToStringAsName` which would use `ToString()` method of instance (not affect dropdown list when selecting type)

**Comment by mackysoft** [comment]
@Antoshidza 
For example, is this good enough?
```cs
[SerializeReference, SubclassSelector]
[ArrayDrawer(CustomLabel = "{LabelName}")]
public List<Item> items1 = new();

[SerializeReference, SubclassSelector]
[ArrayDrawer(CustomLabel = "{ToString()}")]
public List<Item> items2 = new();

[System.Serializable]
public class Item
{
    public string LabelName;
    public int Value;

    public override string ToString () {
        return LabelName;
    }
}
```

**Comment by Antoshidza** [comment]
I'm talking not about customizing array drawing (which is also good way to enhance this package, but array drawing isn't a part of this package responsibilities), but about drawing selected subclass. In my example here it is "Composite Effect" which I'd rather would draw as "Draw card multiple"

**Comment by mackysoft** [comment]
Is this what you want to do?
```cs
[SerializeReference, SubclasSelector(useAsToStringAsName = true)]
public IEffect effect;
```

**Comment by Antoshidza** [comment]
> Is this what you want to do?
> 
> ```cs
> [SerializeReference, SubclasSelector(useAsToStringAsName = true)]
> public IEffect effect;
> ```

Yep

**Comment by mackysoft** [comment]
Functionality implemented. #74 
Publish a release soon, just note that we are using `UNITY_2021_3_OR_NEWER`.
