### ISSUE TITLE
[BUG] OpenUPM Broken

### ISSUE THREAD

**Issue by TyelorD** [mackysoft/Unity-SerializeReferenceExtensions#65]
### What happened?

If you import the package into a Unity Project via OpenUPM, then all of the code is kept from compiling due to the preprocessor macros used.

If I import the .unitypackage directly into my project it works fine, but for some reason when imported through OpenUPM the assembly thinks that `UNITY_2019_3_OR_NEWER` is undefined.

Is it actually necessary to wrap the code with this preprocessor macro? If so, how do we go about getting the code to actually compile when imported through OpenUPM in a way that isn't wonky or hacky?

### Package Version

1.4.0

### Unity Version

6000.0.11f1

**Comment by mackysoft** [comment]
The `UNITY_2019_3_OR_NEWER` directive has been removed in favour of stability.
A new package will be released soon.
