### ISSUE TITLE
[IMPROVE] Foldout rect.x adjustment for Unity 2022.2 or newer

### ISSUE THREAD

**Issue by bulleador** [mackysoft/Unity-SerializeReferenceExtensions#66]
### Improvement destription

[SubclassSelectorDrawer, lines 60 to 64](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/blob/b7d76fb0c5133adc87e09c1d7aea87882a1d812a/Assets/MackySoft/MackySoft.SerializeReferenceExtensions/Editor/SubclassSelectorDrawer.cs#L60) adjust foldout rectangle horizontal position by 12 units to the left for versions 2022.2 or newer like so:
```
#if UNITY_2022_2_OR_NEWER
    // NOTE: Position x must be adjusted.
    // FIXME: Is there a more essential solution...?
    foldoutRect.x -= 12;
#endif
```
which actually makes it render almost outside of the inspector in 2022.3:
![obraz](https://github.com/user-attachments/assets/f0196c0c-5f29-4b51-970f-4fa156d3cdf3)

Removing this adjustment makes the foldout render correctly in 2022.3.

If I find the time, I'll do a PR

**Comment by mackysoft** [comment]
Thank you.
The rendering has been fixed in Unity 6000, 2022.3, 2022.2, 2021.3.
