### ISSUE TITLE
[BUG] Can't select blittable types as `object` / `Object` inheritors

### ISSUE THREAD

**Issue by Antoshidza** [mackysoft/Unity-SerializeReferenceExtensions#69]
### What happened?

```csharp
[SerializeReference, SubclassSelector] private Object _params;
```
This field let me select any type accessible from unity
![image](https://github.com/user-attachments/assets/c08cd2de-bcca-40ac-89af-234aaa675215)
But I can't select `int` / `float` / `bool` / etc. Also `ValueType` doesn't get serialized at all. It is strange, because those blittable types are `object -> ValueType ->` inheritors and should exist in `System` namespace.

### Package Version

1.4.0

### Unity Version

6000.0.19f1

**Comment by mackysoft** [comment]
No serialisation of `System.Object` is assumed.
In the meantime, the latest type search method are pasted below.
```cs
public static IEnumerable<Type> GetTypes (Type baseType)
{
	return TypeCache.GetTypesDerivedFrom(baseType).Append(baseType).Where(p =>
		(p.IsPublic || p.IsNestedPublic || p.IsNestedPrivate) &&
		!p.IsAbstract &&
		!p.IsGenericType &&
		!k_UnityObjectType.IsAssignableFrom(p) &&
		Attribute.IsDefined(p, typeof(SerializableAttribute)) &&
		!Attribute.IsDefined(p, typeof(HideInTypeMenuAttribute))
	);
}
```
