### ISSUE TITLE
[BUG] Properties offset are little bit wrong

### ISSUE THREAD

**Issue by Antoshidza** [mackysoft/Unity-SerializeReferenceExtensions#77]
### What happened?

I see that in v1.6.0 there are some fixes about offsets, but it seems it is still being drawn wrong.
In that example I have hierarchy of types like:
![image](https://github.com/user-attachments/assets/f1126e43-4234-4664-aea3-dfce14a4efc6)

### Package Version

1.6.0

### Unity Version

6000.0.23f1

**Comment by mackysoft** [comment]
As a try, what happens if you install the 1.6.0 unitypackage from Releases and disable line 42 of SubclassSelectorDrawer.cs?
https://github.com/mackysoft/Unity-SerializeReferenceExtensions/releases

![image](https://github.com/user-attachments/assets/ad803734-fda8-447d-8364-ae1295aad5d8)

**Comment by Antoshidza** [comment]
Seems better now
![image](https://github.com/user-attachments/assets/c1331dba-2be2-42ae-82ac-faccb44df335)

**Comment by mackysoft** [comment]
Patch release 1.6.1 has been released.
Thank you!
