### ISSUE TITLE
Property Height Not Updating Immediately [BUG] 

### ISSUE THREAD

**Issue by chadefranklin** [mackysoft/Unity-SerializeReferenceExtensions#9]
### What happened?

When drawing an array of serializable classes (as SerializeField) that contains a SubclassSelector, the property height does not update immediately when changing the type. The weird part is that logging "Debug.Log(EditorGUI.GetPropertyHeight(property,true));" did show it updating immediately. I also wrote my own Custom Property Drawer which does not have this issue, though I cannot figure out why. I have attached a video of the issue.

https://user-images.githubusercontent.com/55667412/160409770-6fb587dd-0f7f-4e1d-85c9-cc87f00fc8b9.mp4

Here is a video of my version without the issue:

https://user-images.githubusercontent.com/55667412/160416646-7cf68072-912b-4ce7-b006-d05c94a9d0d9.mp4

and the code:

https://gist.github.com/chadefranklin/cd2e6c4d89928ce25274395ff8690f9a

### Package Version

1.1.2

### Unity Version

2020.3.30f1

**Comment by mackysoft** [comment]
I have tried to reproduce the problem on my end, but could not.

One possibility is that the process is delegate when the item is selected and is out of the `PropertyDrawer.OnGUI` cycle, so it is not redrawing properly.
![image](https://user-images.githubusercontent.com/13536348/160605335-cdb38135-f43a-438f-b79e-8a88451bc475.png)

---

The following file is the unitypackage for [this branch](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/tree/fix/repaint-immediately).
In this package, `serializedObject.Update()` is called when an item is selected.

This may solve the issue.

[SerializeReference-Extensions.zip](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/files/8371185/SerializeReference-Extensions.zip)

**Comment by chadefranklin** [comment]
Thanks for the help, that may have solved it though I can't tell as I did update my project to 2020.3.32 and this was in the release notes for 2020.3.31:

![image](https://user-images.githubusercontent.com/55667412/161187635-466f4d0e-f63e-4bd2-8279-ac02fd5f5f69.png)
